### ISSUE TITLE
fastX instructions for network down

### ISSUE THREAD

**Issue by astrofle** [aschmiedeke/gbtdocs#1]
The command listed for connecting through the CV fastX: `ssh <machine-name>.gb.nrao.edu startxfce`
can result in an error: `command startxfce not recognized`
an alternative is to use: `ssh <machine-name>.gb.nrao.edu startxfce4` (as in the GB fastX sessions).
This could be noted in the [how to connect remotely if the GBO network is down section](https://gbtdocs.readthedocs.io/en/latest/how-tos/infrastructure/remote-connection.html#what-to-do-if-the-gbo-network-is-down-slow).

**Comment by aschmiedeke** [comment]
Good catch! Indeed it should be startxfce4! I corrected it. New version is online.

**Comment by aschmiedeke** [comment]
Good catch! Indeed it should be startxfce4! I corrected it. New version is online.
