### ISSUE TITLE
VNC Mac instruction edits

### ISSUE THREAD

**Issue by emoravec** [aschmiedeke/gbtdocs#12]
A few requested edits to https://gbtdocs.readthedocs.io/en/latest/how-tos/infrastructure/remote-connection.html#how-do-i-get-the-necessary-software
1. The RealVNC link is broken. Did we mean to link to https://www.realvnc.com/en/connect/download/viewer/ ?
2. We say that "Mac users can use the built-in VNC viewer" but as far as I can tell not all macs have a built in vncviewer. If we mean being able to put `vncviewer` into the terminal and have that work that needs to be installed via homebrew. So we should say that if that is what we mean. 
3. Should we put a recommended way for a Mac user? I think most people use RealVNC but I could be wrong. If someone is doing this the first time I think it would be good to say, we recommend that you start with using RealVNC. 
4. We say that "Mac OS includes a SSH client. You can open a terminal by launching either Terminal or X11, both of which are in your Mac’s Applications > Utilities folder." I think we should clarify by saying, "Mac OS includes a SSH client. You can SSH through a terminal. To open a terminal launch either Terminal or X11, both of which are in your Mac’s Applications > Utilities folder."

**Comment by aschmiedeke** [comment]
re 1. The link was missing the `https://` I've fixed that and now it's working as expected!

I'll work on the other points. I want to reproduce the VNC instructions on my computer first, before I modify any of the Mac instructions. I'll leave the ticket open for now.

**Comment by aschmiedeke** [comment]
I've addressed the other 3 comments in a recent update of the MAC-OS VNC instructions. We'll stick for now with the MacOS built-in VNC viewer (we have more instructions on how to open that) and refer to RealVNC or TigerVNC for people that want to have a third-party vnc viewer. But we won't give detailed instructions on how to use those software.
I'll resolve the issue for now.
