### ISSUE TITLE
Number of M2 feedhorns

### ISSUE THREAD

**Issue by emoravec** [aschmiedeke/gbtdocs#14]
Please update https://gbtdocs.readthedocs.io/en/latest/references/receivers/mustang2/mustang2_overview.html from "MUSTANG-2 is a 223-feedhorn bolometer (continuum) camera with a bandpass from 75 to 105 GHz on the GBT." to "MUSTANG-2 is a bolometer (continuum) camera with ~215 feedhorns and a bandpass from 75 to 105 GHz on the GBT."

**Comment by aschmiedeke** [comment]
Adjusted the text accordingly.
