### ISSUE TITLE
MUSTANG ADS Library Links

### ISSUE THREAD

**Issue by emoravec** [aschmiedeke/gbtdocs#15]
Please update the links to ADS libraries on https://gbtdocs.readthedocs.io/en/latest/references/receivers/mustang2/mustang2_publications.html.

[Library of MUSTANG2 peer reviewed publications](https://ui.adsabs.harvard.edu/user/libraries/1LT-cb7HRMatZGonZYZfVw) should instead be linked to https://ui.adsabs.harvard.edu/public-libraries/1LT-cb7HRMatZGonZYZfVw

[Library of MUSTANG peer reviewed publications](https://ui.adsabs.harvard.edu/user/libraries/sa83k8AzRha8QbLRPTNfdg) should be instead linked to https://ui.adsabs.harvard.edu/public-libraries/sa83k8AzRha8QbLRPTNfdg

**Comment by aschmiedeke** [comment]
I've updated the links accordingly.

**Comment by aschmiedeke** [comment]
I've updated the links accordingly.
