### ISSUE TITLE
Catalog excerpt not formatting correctly

### ISSUE THREAD

**Issue by etsmit** [aschmiedeke/gbtdocs#17]
Under [the pulsar search how-to](https://gbtdocs.readthedocs.io/en/latest/how-tos/observing_modes/pulsars/pulsar_search.html#advanced-use-of-catalogs)

I was unable to format/render the catalog correctly. It is still showing the python formatting, which colors the text weird.

**Comment by aschmiedeke** [comment]
Should be fixed now. Thank you for reporting!
