### ISSUE TITLE
Issue on page /how-tos/observing_modes/pulsars/pulsar_flux_cal.html

### ISSUE THREAD

**Issue by astrofle** [aschmiedeke/gbtdocs#18]
The pulsar flux calibration guide is using line numbers that split the configuration scripts mid-configuration. 
The attached screenshot shows the issue:
<img width="662" alt="Screenshot 2024-09-16 at 9 41 46 PM" src="https://github.com/user-attachments/assets/14e69682-2470-40b6-9b4f-53e1d89decdc">

**Comment by aschmiedeke** [comment]
Thank you Pedro. The line numbers were set incorrectly for the flux cal howto. This is fixed now.
