### ISSUE TITLE
Typo in HI quick guide configuration `swtype`

### ISSUE THREAD

**Issue by astrofle** [aschmiedeke/gbtdocs#2]
https://github.com/aschmiedeke/gbtdocs/blob/eea60a83bd374d5e043b673dff228bfaadc5a8a9/docs/source/how-tos/quick_guides/HI_single-pointing.rst?plain=1#L57

This should say "Specifies type of switching, no switching" or similar.

**Comment by aschmiedeke** [comment]
Great catch. I agree. It is fixed now.
