### ISSUE TITLE
Focus warning in AutoPeak command

### ISSUE THREAD

**Issue by astrofle** [aschmiedeke/gbtdocs#7]
There is a warning related to focus scans and prime focus receivers in the documentation for `AutoPeak`: https://github.com/aschmiedeke/gbtdocs/blob/368eb3bac1bcbb3332464f09aa08940e156ae1d1/sparrow/astrid_commands.py#L157C5-L161C22
This probably should not be in there.

**Comment by aschmiedeke** [comment]
You're right Pedro. This warning should only be present in the documentation for AutoFocus (which is not included in the current documentation yet). I will remove the warning.
